### PR TITLE
Update to Forge 1.12

### PR DESCRIPTION
**Pull request by opencma**
### Prerequisites
* [x] I have read and understand the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly

**Issues Fixed:** Updated to Forge 1.12

### Changes Proposed in this Pull Request

* Moved most embedded libraries to Gradle dependencies - The collective framework is commited, but can be swapped for Gradle managed dependency if/when the 1.12 build is made avaliable in a maven repo. The computercraft and applied energistics mods are not longer in the repo as they can be places in the `run/mods` folder.
* Pocket upgrades are registered via Computercraft's new pocket API.
* All upgrades are functioning. There are minor changes to some implementations. The DynamicMount Lua scripts are not updated.
* Moved from the Chatterbot library to a [Cleverbot API wrapper](https://github.com/Headline22/CleverBotAPI-Java)
* Removed the core mod - It was no longer nessesary since the Computercraft API allows for pocket upgrades
* Moved from NEI to JEI.
* Blocks and items now use the JSON model definitions.
* Updated the Gradle wrapper and ForgeGradle

...

### CODE REVIEW

**Comment by SquidDev** [comment]
Oh wow. As someone currently porting another mod from 1.7.10 to more recent versions I applaud you. 👍

**Comment by austinv11** [comment]
Wow... this PR is amazing. But unfortunately, both @GrandPanda and I have stopped modding Minecraft (and playing it in general) which is why all my mods are currently unmaintained. But since you put so much effort into this update, I'd recommend maintaining a separate fork of this project and maintaining it yourself. I am willing to add links to your forks wherever necessary if you want to do this.

**Comment by rolandoislas** [comment]
@austinv11 I have updated to fork's name and mod id to "PeripheralsPlusOne" and have done the same for the Collective Framework, which is now "The Framework".

They are both pending approval on CurseForge at the moment but should be available at the following locations once they are approved:
- https://minecraft.curseforge.com/projects/peripheralsplusone
- https://minecraft.curseforge.com/projects/the-framework

A link to the [fork](https://github.com/rolandoislas/PeripheralsPlusOne) from the original repo would be appreciated, and if it is not too much trouble, one on CurseForge.

**Comment by austinv11** [comment]
I have added links to your ports. Best of luck!

**Comment by opencma** [comment]
@austinv11 Thank you. Should you wish to pick up the project again, feel free to pull and do so.

**Pull request closed without merging**
